export const Error = {
    ROUTING_ERROR: 1, //RUTA NO EXISTE
    DATABASE_ERROR: 2, //ERROR CON LA BASE DE DATOS
    INVALID_JSON: 3, //JSON ES INVALIDO EN UNA PETICION
    AUTH_ERROR: 4, //ERROR DE AUTENTICACION
    INVALID_PARAM: 5 //ERROR DE PARAMETROS
}